completed react-stopwatch-component challenge
OSAdams/c0121-code-solutions pull request #115
Opened 2021-03-27 00:29 UTC by OSAdams

![react-stopwatch-component](https://user-images.githubusercontent.com/76730244/112704701-edfa8900-8e71-11eb-9459-8c1adabe28ac.gif)

2021-03-27 00:32 UTC, thebearingedge requested changes
Good work so far, almost there!

2021-03-27 00:32 UTC, thebearingedge commented on react-stopwatch-component/src/stopwatch.jsx
> +    return this.setState({ timePassed: 0, isRunning: false });
Pausing the timer should not reset it.

2021-03-27 00:35 UTC, OSAdams commented
![react-stopwatch-component-2](https://user-images.githubusercontent.com/76730244/112704911-ce179500-8e72-11eb-95cc-1ca8b98f42a5.gif)

2021-03-27 00:38 UTC, thebearingedge requested changes
Ok, review the description again, the user should be able to reset the timer if it's currently paused.

2021-03-27 00:38 UTC, thebearingedge commented
By clicking the watch face

2021-03-27 02:09 UTC, OSAdams commented
![react-stopwatch-component-3](https://user-images.githubusercontent.com/76730244/112707201-fbb70b00-8e7f-11eb-8166-00bdd992a113.gif)

2021-03-28 23:35 UTC, thebearingedge approved these changes

2021-03-29 16:07 UTC, merged