String manipulation 2
OSAdams/c0121-code-solutions pull request #116
Opened 2021-03-28 03:54 UTC by OSAdams

![image](https://user-images.githubusercontent.com/76730244/112741917-b7973980-8f57-11eb-87c7-df4f39c803bd.png)

2021-03-28 23:29 UTC, thebearingedge requested changes
Great, just a couple very minor changes.

2021-03-28 23:29 UTC, thebearingedge commented on string-manipulation-2/src/first-chars.js
> +      return string;
You can do this check before your loop begins.

2021-03-28 23:29 UTC, thebearingedge commented on string-manipulation-2/src/num-vowels.js
> +      strArray.push(str[i]);
Instead of pushing the vowels into an array, you can increment a counter.

2021-03-28 23:29 UTC, thebearingedge commented on string-manipulation-2/src/truncate.js
> +  }
You can simplify this code a bit. Try including an immediate `return` if the string is `0` in length. That way you have much less nested logic.

2021-03-29 03:42 UTC, OSAdams commented
![image](https://user-images.githubusercontent.com/76730244/112784274-360ade80-901f-11eb-9aec-288a956c211f.png)

2021-03-29 04:22 UTC, thebearingedge approved these changes

2021-03-29 16:08 UTC, merged