Sgt back end
OSAdams/c0121-code-solutions pull request #136
Opened 2021-07-22 19:37 UTC by OSAdams

![sgt-back-end](https://user-images.githubusercontent.com/76730244/126699328-bebca775-97bd-476b-88d7-dfa12481b228.gif)

2021-08-03 19:50 UTC, TimelikeClosure requested changes

2021-08-03 19:50 UTC, TimelikeClosure commented on sgt-back-end/index.js
> +    `;
In production, `SELECT` columns by-name (rather than blanket `SELECT`s) for better debuggability, performance, and security reasons. `SELECT *` should only be used when you're still figuring out how to formulate your queries: it should never end up saved as part of the app's source code.

2021-08-03 19:50 UTC, TimelikeClosure commented on sgt-back-end/index.js
> +  }
`score` also needs to be an integer, not just any number between `1` and `100` (fractional numbers won't work).

---

![image](https://user-images.githubusercontent.com/16143771/128075819-3047beec-469a-492a-9a3e-cfec63286127.png)

2021-08-03 19:50 UTC, TimelikeClosure commented on sgt-back-end/index.js
> +  }
Fractional `gradeId`s and `score`s are not valid, so they should trigger a `400` error.

---

![image](https://user-images.githubusercontent.com/16143771/128076457-8b0c9793-b11f-4460-b243-815cf1f3dc53.png)

2021-08-03 19:50 UTC, TimelikeClosure commented on sgt-back-end/index.js
> +  }
Fractional `gradeId`s should trigger a `400` error.

---

![image](https://user-images.githubusercontent.com/16143771/128076950-36352d3c-f538-4867-8b8e-ff302014bb82.png)

2021-08-03 19:50 UTC, TimelikeClosure commented on sgt-back-end/index.js
> +          .json(sendStatus);
`204 No Content` should not include any content (no response body).

2021-08-17 16:42 UTC, OSAdams commented
![image](https://user-images.githubusercontent.com/76730244/129766459-b4c7570a-fe5f-47bb-9436-0367c66b4ae3.png)

2021-08-17 21:47 UTC, TimelikeClosure approved these changes

2021-08-18 15:48 UTC, merged