React app drawer component
OSAdams/c0121-code-solutions pull request #137
Opened 2021-08-03 01:57 UTC by OSAdams

![react-app-drawer-component](https://user-images.githubusercontent.com/76730244/127945565-5f190801-4411-47f1-86b7-1c815e31a7ab.gif)

2021-08-03 19:26 UTC, TimelikeClosure requested changes

2021-08-03 19:26 UTC, TimelikeClosure commented on react-app-drawer-component/dist/styles.css
> +  width: 100vh;
Setting full-`width` on block-level elements is generally a bad idea: https://github.com/Learning-Fuze/curriculum/tree/master/guides/effective-css#width

Also, there probably isn't a need to scale the `width` based on the _height_ of the page.

2021-08-03 19:26 UTC, TimelikeClosure commented on react-app-drawer-component/dist/styles.css
> +  font-size: 25px;
Stick with `rem` on font sizes: https://github.com/Learning-Fuze/curriculum/tree/master/guides/effective-css#font-size

2021-08-03 19:26 UTC, TimelikeClosure commented on react-app-drawer-component/src/app-drawer.jsx
> +  }
In general, your apps will be more stable if you have separate dedicated methods for showing vs hiding things, rather than one that acts as a toggle.

2021-08-04 15:59 UTC, TimelikeClosure commented on react-app-drawer-component/dist/styles.css
> +  width: 100vh;
![image](https://user-images.githubusercontent.com/16143771/128214220-e3745181-c42b-4f45-8ecc-82a4e55d25fc.png)

---

![image](https://user-images.githubusercontent.com/16143771/128214122-39442cc9-06c1-4f4d-a3ab-183b9a526091.png)

2021-08-06 13:18 UTC, OSAdams commented
![react-app-drawer-component-2](https://user-images.githubusercontent.com/76730244/128516200-76e16814-52d3-4a0e-a61c-37e1ef31835a.gif)

2021-08-06 22:46 UTC, TimelikeClosure approved these changes

2021-08-07 00:04 UTC, merged