React accordion component
OSAdams/c0121-code-solutions pull request #139
Opened 2021-08-30 14:41 UTC by OSAdams

![react-accordion-component](https://user-images.githubusercontent.com/76730244/131357120-d7e58f08-c9fe-4e6a-b657-929feeec8d5a.gif)

2021-10-07 19:06 UTC, OSAdams commented
![react-accordion-component-v2](https://user-images.githubusercontent.com/76730244/136446954-f20499f4-247f-4628-b68e-a5ce770fd261.gif)

2021-11-03 17:21 UTC, TimelikeClosure requested changes

2021-11-03 17:21 UTC, TimelikeClosure commented on react-accordion-component/src/accordion.jsx
> +  }
Opening one topic should close the other topics:

---

![image](https://user-images.githubusercontent.com/16143771/140147391-a324dab3-2046-46e0-b29a-57e8f00ed1ac.png)

2021-11-13 20:11 UTC, OSAdams commented
![react-carousel-component-2](https://user-images.githubusercontent.com/76730244/141657701-3fa1a746-26fb-4304-9eff-d383cad2ecea.gif)

2021-11-16 05:25 UTC, TimelikeClosure approved these changes

2021-11-16 23:00 UTC, merged