Javascript carousel
OSAdams/c0121-code-solutions pull request #62
Opened 2021-02-18 01:10 UTC by owen-adams2021

![image](https://user-images.githubusercontent.com/76730244/108289248-1a790200-715c-11eb-8012-2e38abc4d447.png)

2021-02-19 19:26 UTC, codingcodymiller requested changes
Great work so far!! Please see my notes

2021-02-19 19:26 UTC, codingcodymiller commented on javascript-carousel/main.js
> +  }
Same here, make use of an array

2021-02-19 19:26 UTC, codingcodymiller commented on javascript-carousel/main.js
> +  }
Rather than having an individual conditional for each possible url, this would be better as an array storing the urls that you can determine the current index of, and move forward to the next index.

2021-03-23 18:25 UTC, thebearingedge requested changes
Hi Owen, please let me know when this is ready for review again. I saw your last commit message said "Work in progress." So I'm just updating this for my records.

2021-04-25 23:40 UTC, OSAdams commented
![js-carousel](https://user-images.githubusercontent.com/76730244/116013408-0b03b280-a5fe-11eb-95ef-8b7cd43dab6d.gif)

2021-04-28 02:50 UTC, thebearingedge requested changes

2021-04-28 02:50 UTC, thebearingedge commented on javascript-carousel/main.js
> +});
Instead of adding individual event listeners to each circle, add one event listener to their parent element (event delegation). You can loop through all of the circles and `if ($allCircles[i] === event.target)` then you can update the class to be a filled circle, or not.

2021-04-28 07:49 UTC, OSAdams commented
![js-carousel2](https://user-images.githubusercontent.com/76730244/116366931-cd0cb700-a7d4-11eb-812b-e834a4842384.gif)

2021-04-28 19:20 UTC, thebearingedge approved these changes
Much, much better, my dude.

2021-04-28 19:42 UTC, OSAdams commented
Thanks! It took me a handful of google searches to find the children method of the parent object. Now I don't get upset looking at that code, lol

2021-04-28 19:42 UTC, merged