Array manipulation 3
OSAdams/c0121-code-solutions pull request #66
Opened 2021-03-07 23:24 UTC by OSAdams

![image](https://user-images.githubusercontent.com/76730244/110258775-4c6ad080-7f72-11eb-8877-94f9ae330fa4.png)

2021-03-08 00:35 UTC, thebearingedge requested changes

2021-03-08 00:35 UTC, thebearingedge commented on array-manipulation-3/src/difference.js
> +}
Please rewrite this without arrow functions, spread, or filter. It's very risky to turn in code you are not prepared to fully explain.

2021-03-08 00:35 UTC, thebearingedge commented on array-manipulation-3/src/zip.js
> +  }
If you decide which array is shorter, you can write one loop.

```js
var length = Math.min(first.length, second.length);
```

2021-03-10 02:35 UTC, thebearingedge requested changes

2021-03-10 02:35 UTC, thebearingedge commented on array-manipulation-3/src/difference.js
> +}
This function can be simplified a bit. Try this strategy:
- create a new empty array
- loop through the first array
- for each value
    - if the value is not in the second array, put it in the new array
- loop through the second array
- for each value
    - if the value is not in the first array, put it in the new array
- return the new array

2021-03-15 16:55 UTC, OSAdams commented
![image](https://user-images.githubusercontent.com/76730244/111190637-a892ad80-858d-11eb-942f-b81d790c8807.png)

2021-03-15 19:54 UTC, thebearingedge approved these changes

2021-03-15 19:56 UTC, merged