completed express-post-json exercise
OSAdams/c0121-code-solutions pull request #88
Opened 2021-03-16 23:02 UTC by OSAdams

gif of Cmder log

![express_1](https://user-images.githubusercontent.com/76730244/111391010-1fad6c00-868a-11eb-88c2-e7102e704d26.gif)

2021-03-16 23:04 UTC, thebearingedge requested changes
Great, just one line needs to be changed.

2021-03-16 23:04 UTC, thebearingedge commented on express-post-json/index.js
> +  res.sendStatus(204);
The client should receive a status code of `201` as well as the added grade object.

2021-03-16 23:24 UTC, OSAdams commented
![image](https://user-images.githubusercontent.com/76730244/111392581-48833080-868d-11eb-92d8-4ddc33dd2676.png)

2021-03-17 00:25 UTC, thebearingedge approved these changes

2021-03-17 00:26 UTC, merged